name: GitHub AI daily report
    on:
      schedule:
        - cron: '0 0   *'
      workflow_dispatch:
    jobs:
      send-report:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-python@v5
            with:
              python-version: '3.11'
          - env:
              SMTP_SERVER: smtp.163.com
              SMTP_PORT: '994'
              SENDER_ADDRESS: ${{ secrets.SENDER_ADDRESS }}
              SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
              RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
            run: python report.py
